repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/Lucas-C/pre-commit-hooks-markup
  rev: v1.0.1
  hooks:
  - id: rst-linter
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.0
  hooks:
    - id: check-readthedocs
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black

