repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: '0.27.0'
  hooks:
    - id: check-readthedocs
- repo: https://github.com/thclark/pre-commit-sphinx
  rev: '0.0.3'
  hooks:
    - id: build-docs
      args: ['--html-dir', 'docs/html', '--source-dir', 'docs/source']
      language_version: python3
-   repo: https://github.com/psf/black
    rev: '23.9.1'
    hooks:
    - id: black
    args: [--line-length=120]
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      args: [--max-line-length=120, "--exclude=docs/source/conf.py"]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
-   repo: https://github.com/python-poetry/poetry
    rev: '1.6.0'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
