[tool.poetry]
name = "pydesigner"
version = "1.1.0"
description = "A hands-free DTI, DKI, FBI and FBWM preprocessing pipeline"
authors = ["Siddhartha Dhiman <sid.kill3r@gmail.com>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = ">=3.8"
numpy = "^1.24.3"
scipy = "^1.5.0"
joblib = "^1.2.0"
tqdm = "^4.65.0"
multiprocess = "^0.70.14"
nibabel = "^5.1.0"
dipy = "^1.7.0"
cvxpy = "^1.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
