__maxdtibval__ = 1.5    # maximum DTI B-value
__mindtibval__ = 0.5    # minimum DTI B-value
__maxdkibval__ = 2.5    # minimum DTI B-value
__mindkibval__ = 0.5    # maximum DKI B-value
__minfbibval__ = 4.0    # minimum FBI B-value
__d0__ = 3.0            # diffusivity of free water at body temp (37 deg C) for upper bound on Da
__dn__ = 1.5            # estimated intra-neurite diffusivity in mm^2/ms
__pkT__ = 0.4           # peak thresholding for white matter fiber tracking
__minZero__ = 10e-8      # threshold under which all numbers are zero
__dirs__ = 256          # Define number of directions to resample after computing all tensors 
