#!/bin/bash
# Downloads and extractslatest release PyDesigner into /tmp/PyDesigner
mkdir -p /tmp/PyDesigner
export URL=$(curl -s https://api.github.com/repos/m-ama/PyDesigner/releases/latest | grep "tarball" | cut -d '"' -f 4)
wget -q -O - $URL | tar -xzvf - -C /tmp/PyDesigner --strip 1