name: CI

on:
  pull_request:
  push:
    branches: [main]


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_BRIDGE_PAT }}

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
        architecture: 'x64'

    - name: Run Pre-Commit
      id: pre-commit
      uses: pre-commit/action@v3.0.0
      continue-on-error: true
      with:
        extra_args: --all-files

    - name: Auto-commit changed files
      id: git-auto-commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Pre-commit autofix"

    - name: Return pre-commit response
      if: steps.pre-commit.outcome == 'failure'
      run: exit 1
